### ISSUE TITLE
pull request closed token not validated? why & help

### ISSUE THREAD

**Issue by shhitzelectric** [jup-ag/token-list#1248]
### Discussed in https://github.com/jup-ag/token-list/discussions/1247

<div type='discussions-op-text'>

<sup>Originally posted by **shhitzelectric** January 23, 2024</sup>
I recently opened a pull request to validate a token and it had been on the list for a couple of weeks and it was just recently closed I do not know why and I would like some help trying to fix this can somebody please help. @9yoi </div>

**Comment by xenothales** [comment]
send the Pull Request. Can't help if you don't show the problem.

**Comment by shhitzelectric** [comment]
https://github.com/jup-ag/token-list/pull/1012

**Comment by shhitzelectric** [comment]
Did you receive the link?

**Comment by shhitzelectric** [comment]
> Looks like you used "Main" as the title of your PR. They say not to do that, read the file you sent in your Pull Request. It says it at the bottom.

thank you! how do i change that will you please help
