### ISSUE TITLE
PR closed

### ISSUE THREAD

**Issue by Ragul84** [jup-ag/token-list#1249]
Though my token had passed all the given criterias by jupiter, the pulll request has been closed without any solid reasons for not merging it. I would like the responsible team member to explain why my PR can't be merged, is it because of my name and the country of my origin? My PR was for $MINE Minecraft

**Comment by shhitzelectric** [comment]
good question seems as im not the only one, hopefully its not a bias decision. it would be nice for them to at least give reasons why and possible solutions. some help and possible guidance and to work by github guidelines and merge the obvious real tokens, LIKE SHHITZELECTRIC
