### ISSUE TITLE
Validation for $SWTS

### ISSUE THREAD

**Issue by Sweetscoin** [jup-ag/token-list#189]
Zedz from Sweets Coin - I can hereby attest that the provided information are accurate, and the token is valid.

☑Mint address: 5SwxhEunuUUcWe4ojybdDwky6dpLxAehNmF4AA71STNh
☑Symbol: $SWTS
☑Token Decimals: 5
☑Token icon: https://ibb.co/Pzvtq0S
☑ On-chain metadata matches
☑No duplication on Jupiter's strict list
☑ Is Listed on Coingecko / CMC

☑ I did not modify unrelated code.
☑ My change matches the format in the file (no spaces between fields).
☑ My token is already live and trading on Jupiter.
☑ !!! I read the README section on Community-Driven Validation and will get community support on Tw

**Comment by meijiao** [comment]
Please read the README and open a PR instead.
