### ISSUE TITLE
Help to validate Token for Jupter

### ISSUE THREAD

**Issue by pngmangii** [jup-ag/token-list#2067]
Can't seem to create a pull request to validate Token for Jupter
The create function dosnt come oun

<img width="1277" alt="Help" src="https://github.com/jup-ag/token-list/assets/26833648/3d0c103f-2f1a-400d-8c39-b863114d6705">

**Comment by DiscoveryMuffin** [comment]
The same problem. I don't know how to add PR. Help will be appreciated.
