### ISSUE TITLE
Validate VersusCoin

### ISSUE THREAD

**Issue by vscn-bet** [jup-ag/token-list#2761]
[ X ] Mint address: 4GCJwmLfuk1F6s5Z6TxeLoBYQocaDh9yNLFxPokDHV7r
[ X ] Symbol: VSCN
[ X ] Token Decimals: 6
[ X ] Token icon: https://vscn.bet/img/logo.png
[ X ] On-chain metadata matches
[ X ] No duplication on Jupiter's strict list

We're working really hard on our platform. Please validate.
PR: https://github.com/jup-ag/token-list/pull/2628

**Comment by Diamondcityk** [comment]
> [ X ] Mint address: 4GCJwmLfuk1F6s5Z6TxeLoBYQocaDh9yNLFxPokDHV7r
> 
> [ X ] Symbol: VSCN
> 
> [ X ] Token Decimals: 6
> 
> [ X ] Token icon: https://vscn.bet/img/logo.png
> 
> [ X ] On-chain metadata matches
> 
> [ X ] No duplication on Jupiter's strict list
> 
> 
> 
> We're working really hard on our platform. Please validate.
> 
> PR: https://github.com/jup-ag/token-list/pull/2628
> 
>
