### ISSUE TITLE
Validate [Brock]https://solscan.io/token/F6wgrTy4WHwNWZyiZrJKqPZMYhgGppyiQnnKo9rNP2JW)

### ISSUE THREAD

**Issue by theguysaccount** [jup-ag/token-list#2888]
Validate [Brock](https://solscan.io/token/F6wgrTy4WHwNWZyiZrJKqPZMYhgGppyiQnnKo9rNP2JW)
Attestations (Please provide links):
Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://twitter.com/Cogent_Crypto/status/1630963084037869569 The quoted tweet provides significant evidence of community support. https://x.com/BrockCoinSol/status/1780174136150503427
Coingecko/ CMC URL (If available): Awaiting Approval
Validation (Please check off boxes):
YES  The metadata provided in the PR matches what is on-chain (Mandatory)
YES Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will de delayed)
NO  Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) 
Acknowledgement (Please check off boxes)
YES I did not modify unrelated code.
 YES My change matches the format in the file (no spaces between fields).
YES  My token is already live and trading on Jupiter.
YES I read the README section on Community-Driven Validation and will get community support on Twitter.

**Comment by Janani321** [comment]
Nice brock.

**Comment by Tim-Alpha** [comment]
Awesome ✌🏻

**Comment by WebDevVanguard** [comment]
Yeah✌️

**Comment by theguysaccount** [comment]
I saw this was closed, yet I didnt see any update and its not showing on strict list?

**Comment by theguysaccount** [comment]
@9yoi
