### ISSUE TITLE
Validate $Brock

### ISSUE THREAD

**Issue by theguysaccount** [jup-ag/token-list#2983]
Attestations (Please provide links):

Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: The quoted tweet provides significant evidence of community support. 
https://x.com/BrockCoinSol/status/1780174136150503427

Validation (Please check off boxes):
YES The metadata provided in the PR matches what is on-chain (Mandatory)

YES Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will de delayed)

NO Is Listed on Coingecko / CMC (Optional, but helpful for reviewers)

Acknowledgement (Please check off boxes)
YES I did not modify unrelated code.
YES My change matches the format in the file (no spaces between fields).
YES My token is already live and trading on Jupiter.
YES I read the README section on Community-Driven Validation and will get community support on Twitter.

Website: https://BrockCoinSol.com

Had prior ticket say closed, but not completed. Had 5 comments from other Github users. 

Thanks for the help.

**Comment by xelax86** [comment]
Hi, thank you all for the fantastic work and my first coin and it's based on a real project the link is:
https://x.com/venepawer/status/1782590645762228386?s=46&t=QGtcVLOeuBRC3GyiyjetvA

to the three questions yes, the code is the same, and I hope the token has already been created and present
Thank you
