### ISSUE TITLE
> > * [x]    Mint address: 5VsGFkHjRgXgE6YWJpWQbauTn4Q1aEfXDgMupeMVHa9E

### ISSUE THREAD

**Issue by mahrdika01** [jup-ag/token-list#299]
> > * [x]    Mint address: 5VsGFkHjRgXgE6YWJpWQbauTn4Q1aEfXDgMupeMVHa9E
> > * [x]    Symbol: CAPTAIN
> > * [x]    Token Decimals: 9
> > * [x]    Token icon: https://krjkv4fz2kvy5vyqwjpky43cjf7n7coz7ljh3znacywvoa7xiooa.arweave.net/VFKq8LnSq47XELJerHNiSX7fidn60n3loBYtVwP3Q5w
> > * [x]    On-chain metadata matches
> > * [x]    No duplication on Jupiter's strict list
> 
> Please Support Our Validate Request Thank's

_Originally posted by @captainsolan in https://github.com/jup-ag/token-list/issues/296#issuecomment-1684383610_

**Comment by Timoon21** [comment]
Please open a PR, not an issue

**Comment by Timoon21** [comment]
Please open a PR, not an issue
