### ISSUE TITLE
Space X on Solana

### ISSUE THREAD

**Issue by cdia126** [jup-ag/token-list#3132]
FRAUD TokEN...   Hide behind wallet address

**Comment by sirfoufou** [comment]
Thank you for bringing this to our attention. As a community, we take such matters seriously.
 If you suspect fraudulent activity related to this token, please follow these steps:

1-Report Content:
Click the three dots (usually located in the upper-right corner of the comment).
Select “Report content”.
You may see options to report to repository admins or report abuse to GitHub Support

2-Provide Evidence:
If possible, provide additional context or evidence that supports your claim.
Mention any specific behaviors or patterns that raise concerns.

3-Community Moderation:
Our community relies on vigilance and collaboration.
Moderators and community members will review the situation.
If the token is indeed fraudulent, appropriate actions will be taken.

Remember that maintaining a safe and trustworthy environment is essential for everyone in the community. 
Let’s work together to ensure the integrity of our ecosystem! 🚀🔍
