### ISSUE TITLE
Add Pedro the Raccoon to the Strict list

### ISSUE THREAD

**Issue by PedroDancing** [jup-ag/token-list#3197]
Please let us on the Strict list, we started a CTO ate the 09.04.24. Im sure you saw the meme we are growing exponentially. We are completely organic.

**Comment by sirfoufou** [comment]
Sure, 
Thank you for your interest in being listed on the Strict list! We appreciate your enthusiasm and the organic growth of your project.

**Comment by PedroDancing** [comment]
Nice, how long will it take until we’re on the strict list?
Please let me know if there is anything else you need from us.
Thanks for the quick response
