### ISSUE TITLE
Please Add one punch man to the strict list.

### ISSUE THREAD

**Issue by OnePunchManSaitama** [jup-ag/token-list#3817]
Good day, 

Our completely organic C.T.O. has started 6 days ago, the DEV had a nice hamburger and milkshake from it.
We made him regret that, right now we have been building our community exponentially and we would love to be on your strict list!

Kind regards, 

One Punch Community.

**Comment by AndreiT1310** [comment]
Let’s gooo #saitama

**Comment by CryptoAndre24** [comment]
SAITAMA THE JEET PUNCHER 

🤜🏽🔥🤛🏽

🐺PACK TO CONQUER THE MEME SPACE 🚀

**Comment by PleaseBePatient1** [comment]
Saitama needs to be everywhere! Community, community, community...

**Comment by Shilohmon** [comment]
The reboot will severe! #Saitama
